FROM node:18
WORKDIR /app

# Copiar archivos de dependencias primero
COPY package*.json ./

# Instalar dependencias (aquí se espera que exista express en package.json)
RUN npm install

# Copiar el resto del código fuente
COPY . .

EXPOSE 3001
CMD ["node", "server.js"]
