-- MySQL Script generated by MySQL Workbench
-- Sun Oct 26 19:43:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inmuebles_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inmuebles_db` ;

-- -----------------------------------------------------
-- Schema inmuebles_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inmuebles_db` DEFAULT CHARACTER SET utf8 ;
USE `inmuebles_db` ;

-- -----------------------------------------------------
-- Table `inmuebles_db`.`TblInmuebles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmuebles_db`.`TblInmuebles` ;

CREATE TABLE IF NOT EXISTS `inmuebles_db`.`TblInmuebles` (
  `IdInmueble` INT NOT NULL AUTO_INCREMENT,
  `Precio` INT NULL,
  `Ambientes` INT NULL,
  `Banos` INT NULL,
  `Garage` INT NULL,
  `Balcon` INT NULL,
  `Metros_cuadrados` INT NULL,
  `Fotodir` VARCHAR(250) NULL,
  `Titulo` VARCHAR(250) NULL,
  `Resumen` VARCHAR(250) NULL,
  `Descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`IdInmueble`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmuebles_db`.`TblBusqueda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmuebles_db`.`TblBusqueda` ;

CREATE TABLE IF NOT EXISTS `inmuebles_db`.`TblBusqueda` (
  `IdBusqueda` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Ambientes` INT NULL,
  `Precio` INT NULL,
  `Barrio` VARCHAR(100) NULL,
  `Provincia` VARCHAR(100) NULL,
  PRIMARY KEY (`IdBusqueda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmuebles_db`.`TblDirecciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmuebles_db`.`TblDirecciones` ;

CREATE TABLE IF NOT EXISTS `inmuebles_db`.`TblDirecciones` (
  `IdDireccion` INT NOT NULL AUTO_INCREMENT,
  `IdInmueble` INT NOT NULL,
  `IdCalle` INT NULL,
  `Numero` INT NULL,
  `Piso` INT NULL,
  `Puerta` INT NULL,
  `IdCodigoPostal` INT NULL,
  PRIMARY KEY (`IdDireccion`),
  INDEX `ndx_calle` (`IdCalle` ASC) VISIBLE,
  INDEX `ndx_codigopostal` (`IdCodigoPostal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmuebles_db`.`TblPartido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmuebles_db`.`TblPartido` ;

CREATE TABLE IF NOT EXISTS `inmuebles_db`.`TblPartido` (
  `IdPartido` INT NOT NULL,
  `Descripcion` VARCHAR(100) NULL,
  `idProvincia` INT not NULL,
  PRIMARY KEY (`IdPartido`),
  INDEX `idProvincia_index` (`IdProvincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmuebles_db`.`TblCodigoPostal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmuebles_db`.`TblCodigoPostal` ;

CREATE TABLE IF NOT EXISTS `inmuebles_db`.`TblCodigoPostal` (
  `IdCodigoPostal` INT NOT NULL,
  `Descripcion` VARCHAR(15) NULL,
  `IdPartido` INT NULL,
  PRIMARY KEY (`IdCodigoPostal`),
  INDEX `ndx_partido` (`IdPartido` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmuebles_db`.`TblCalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmuebles_db`.`TblCalles` ;

CREATE TABLE IF NOT EXISTS `inmuebles_db`.`TblCalles` (
  `IdCalle` INT NOT NULL,
  `Descripcion` VARCHAR(100) NULL,
  `IdCodigoPostal` INT NULL,
  PRIMARY KEY (`IdCalle`),
  INDEX `FK_Calles_cp_idx` (`IdCodigoPostal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmuebles_db`.`TblProvincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmuebles_db`.`TblProvincia` ;

CREATE TABLE IF NOT EXISTS `inmuebles_db`.`TblProvincia` (
  `IdProvincia` INT NOT NULL,
  `Descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`IdProvincia`))
ENGINE = InnoDB;

USE `inmuebles_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `inmuebles_db`.`v_inmuebles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmuebles_db`.`v_inmuebles` (
  `numero_inm` INT, 
  `foto_inm` VARCHAR(250), 
  `titulo_inm` VARCHAR(250),
  `resumen_inm` VARCHAR(250),
  `descripcion_inm` VARCHAR(250),
  `Precio` INT, 
  `ambientes` INT, 
  `banios` INT, 
  `garage` INT, 
  `balcon` INT, 
  `metros_cuadrados` INT, 
  `calle` INT, 
  `numero` INT, 
  `piso` INT, 
  `codigo_postal` INT,
  `partido_barrio` INT,
  `provincia` INT);

-- -----------------------------------------------------
-- View `inmuebles_db`.`v_inmuebles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmuebles_db`.`v_inmuebles`;
DROP VIEW IF EXISTS `inmuebles_db`.`v_inmuebles` ;
USE `inmuebles_db`;
CREATE  OR REPLACE VIEW `v_inmuebles` AS
    SELECT 
        inm.IdInmueble numero_inm,
        inm.Fotodir foto_inm,
        inm.titulo titulo_inm,
        inm.resumen resumen_inm,
        inm.descripcion descripcion_inm,
        inm.Precio,
        inm.ambientes ambientes,
        inm.banos banios,
        inm.garage garage,
        inm.balcon, 
        inm.metros_cuadrados,
        cal.descripcion calle,
        dirs.numero numero,
        dirs.piso piso,
        -- no se incluye la puerta, solo es busqueda en la web --
        cp.descripcion codigo_postal,
        par.descripcion partido_barrio,
        prov.descripcion provincia
    FROM
        TblInmuebles inm inner join TblDirecciones dirs on inm.IdInmueble=dirs.IdInmueble
        inner Join TblCalles cal on cal.Idcalle=dirs.IdCalle
        inner join TblCodigoPostal cp on cp.IdCodigoPostal=dirs.IdCodigoPostal
        inner join TblPartido par on par.IdPartido=cp.IdPartido
        inner Join TblProvincia prov on prov.idProvincia=par.IdProvincia;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
