-- MySQL Script generated by MySQL Workbench
-- Sun Oct 26 19:43:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

USE `inmuebles_db` ;


-- 1 - Partidos / Barrios
insert TblPartido set IdPartido=1, Descripcion='Caballito', idProvincia=1;
insert TblPartido set IdPartido=2, Descripcion='Floresta', idProvincia=1;
insert TblPartido set IdPartido=3, Descripcion='Villa Ballester', idProvincia=2;
insert TblPartido set IdPartido=4, Descripcion='Laferrere', idProvincia=2;

-- 2 - Provincias
insert TblProvincia set idProvincia=1, Descripcion='CABA';
insert TblProvincia set idProvincia=2, Descripcion='Provincia Buenos Aires';

-- 3 - Inmuebles
insert TblInmuebles set Precio=100000, Ambientes=3, banos=1, garage=0, Balcon=0, Metros_cuadrados=40, Fotodir='src/img/depto_caballito.jpg', titulo='Depto 3 amb', resumen='Departamento de 3 ambientes en caballito', descripcion='Departamento pequeño en caballito de 40mts, de 3 ambientes, baño, cerca de avenida san martin. ';
insert TblInmuebles set Precio=250000, Ambientes=5, banos=2, garage=1, Balcon=1, Metros_cuadrados=100, Fotodir='src/img/depto_Flores.jpg', titulo='Depto Familiar', resumen='Departamento familiar amplio en Floresta', descripcion='Departamento Familiar en caballito de 100mts, de 5 ambientes, 2 baño, Garage y con Balcon, cerca de Alvarez Jonte. ';
insert TblInmuebles set Precio=100000, Ambientes=3, banos=1, garage=1, Balcon=1, Metros_cuadrados=70, Fotodir='src/img/depto_vballester.jpg', titulo='Depto 3 amb', resumen='Departamento de 3 ambientes en Villa Ballester', descripcion='Departamento en Villa Ballester de 70mts, de 3 ambientes, baño, GArage y Balcon cerca de la Estacion de Tren. ';
insert TblInmuebles set Precio=10000, Ambientes=2, banos=1, garage=0, Balcon=0, Metros_cuadrados=40, Fotodir='src/img/casa_laferrere.jpg', titulo='Casa 2 amb', resumen='Casa de 2 ambientes en Laferrere', descripcion='Casa en Laferrere de 40mts, de 2 ambientes, baño, cerca de la Estacion de Tren. Detalles a reparar. ';

-- 4 - Direcciones
insert TblDirecciones set IdInmueble=1, IdCalle=1, numero=4430, piso=3, puerta=2, IdCodigoPostal=1;
insert TblDirecciones set IdInmueble=2, IdCalle=2, numero=3220, piso=0, puerta=1, IdCodigoPostal=2;
insert TblDirecciones set IdInmueble=3, IdCalle=3, numero=5000, piso=2, puerta=4, IdCodigoPostal=3;
insert TblDirecciones set IdInmueble=4, IdCalle=4, numero=6250, piso=0, puerta=1, IdCodigoPostal=4;

-- 5 - Codigos Postales
insert TblCodigoPostal set IdCodigoPostal=1, Descripcion='C1400', IdPartido=1;
insert TblCodigoPostal set IdCodigoPostal=2, Descripcion='C1700', IdPartido=2;
insert TblCodigoPostal set IdCodigoPostal=3, Descripcion='11700', IdPartido=3;
insert TblCodigoPostal set IdCodigoPostal=4, Descripcion='90700', IdPartido=4;

-- 6 - Calles
insert TblCalles set Idcalle=1, Descripcion='Avenida Honorio Pueyrredon', IdCodigoPostal=1;
insert TblCalles set Idcalle=2, Descripcion='Avenida Alvarez Jonte', IdCodigoPostal=2;
insert TblCalles set Idcalle=3, Descripcion='Calle Republica', IdCodigoPostal=3;
insert TblCalles set Idcalle=4, Descripcion='Avenida de los Muertos', IdCodigoPostal=4;




